# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cpi', models.IntegerField()),
                ('Year', models.CharField(choices=[('i', 'First'), ('ii', 'Second'), ('iii', 'Third'), ('iv', 'Fourth'), ('v', 'Fifth')], max_length=3)),
                ('Department', models.CharField(choices=[('cse', 'computer science'), ('mec', 'mechanical engineering'), ('mnc', 'mathematica and computing')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
