# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160909_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpi',
            field=models.IntegerField(null=True),
        ),
    ]
