# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160910_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Department',
            field=models.CharField(choices=[('cse', 'computer science'), ('mec', 'mechanical engineering'), ('mnc', 'mathematica and computing')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Year',
            field=models.CharField(choices=[('i', 'First'), ('ii', 'Second'), ('iii', 'Third'), ('iv', 'Fourth'), ('v', 'Fifth')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
