# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160910_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Department',
        ),
        migrations.AddField(
            model_name='person',
            name='dept',
            field=models.CharField(choices=[('cse', 'computer science'), ('mec', 'mechanical engineering'), ('mnc', 'mathematica and computing')], max_length=3, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpi',
            field=models.IntegerField(null=True, verbose_name='CPI'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
    ]
